{"name": "test_account_wrong_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'get'", "trace": "self = <testCases.testLogin.test_login.TestSearchPage object at 0x10d62d320>, state_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x10d581518>\n\n    @allure.story('这是一个测试账号错误登录的case')\n    def test_account_wrong_login(self,state_login_class):\n        '''\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        '''\n>       state_login_class.get_login_url()\n\ntestCases/testLogin/test_login.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nOperationalLayer/Login/login.py:18: in get_login_url\n    self.get_url()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <OperationalLayer.Login.login.LoginOperate object at 0x10d581518>\n\n    def get_url(self):\n>       return self.driver.get(self.url)\nE       AttributeError: 'function' object has no attribute 'get'\n\nBase/base.py:52: AttributeError"}, "description": "\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'get'\n", "trace": "  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/kouhui/Desktop/自动化文件/ui-automatic/OperationalLayer/Login/login.py\", line 18, in get_login_url\n    self.get_url()\n  File \"/Users/kouhui/Desktop/自动化文件/ui-automatic/Base/base.py\", line 52, in get_url\n    return self.driver.get(self.url)\n"}, "start": 1577152044598, "stop": 1577152044599}], "start": 1577152044598, "stop": 1577152044603, "uuid": "cb4c8bc5-5d76-49d0-9645-566baede3a1f", "historyId": "fd7bdb65f4df5754da250d662b7e39f5", "testCaseId": "70ff1461dbd22ac420eff06f2f2ffeba", "fullName": "testCases.testLogin.test_login.TestSearchPage#test_account_wrong_login", "labels": [{"name": "story", "value": "这是一个测试账号错误登录的case"}, {"name": "feature", "value": "登录"}, {"name": "parentSuite", "value": "testCases.testLogin"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSearchPage"}, {"name": "host", "value": "kouhuideMacBook-Air.local"}, {"name": "thread", "value": "48838-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.testLogin.test_login"}]}