{"name": "test_account_wrong_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert '\\n\\t\\t\\t\\t\\t...录\\n\\t\\t\\t\\t\\t' == '登录信息有误，请确认后重新登录'\n  - \n  - \t\t\t\t\t\t登录信息有误，请确认后重新登录\n  ? ------               -\n  + 登录信息有误，请确认后重新登录\n  -", "trace": "self = <testCases.testLogin.test_login.TestSearchPage object at 0x108752e48>, state_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x10879f4a8>\n\n    @allure.story('这是一个测试账号错误登录的case')\n    def test_account_wrong_login(self, state_login_class):\n        '''\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        '''\n        state_login_class.get_login_url()\n        state_login_class.input_account(abnormal_login_data.account, abnormal_login_data.password,\n                                        abnormal_login_data.verification_code)\n        state_login_class.confirm_login_button()\n        time.sleep(1)\n>       assert state_login_class.validate_account_not_exist() == '登录信息有误，请确认后重新登录'\nE       AssertionError: assert '\\n\\t\\t\\t\\t\\t...录\\n\\t\\t\\t\\t\\t' == '登录信息有误，请确认后重新登录'\nE         - \nE         - \t\t\t\t\t\t登录信息有误，请确认后重新登录\nE         ? ------               -\nE         + 登录信息有误，请确认后重新登录\nE         -\n\ntestCases/testLogin/test_login.py:41: AssertionError"}, "description": "\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "passed", "start": 1577176655129, "stop": 1577176656024}, {"name": "步骤2：输入账号，密码，验证码", "status": "passed", "parameters": [{"name": "account", "value": "'admin1'"}, {"name": "password", "value": "'admin123'"}, {"name": "verification_code", "value": "'1111'"}], "start": 1577176656025, "stop": 1577176656588}, {"name": "步骤3：点击登录按钮", "status": "passed", "start": 1577176656588, "stop": 1577176656652}, {"name": "步骤4：获取账号不存在报错信息", "status": "passed", "start": 1577176657657, "stop": 1577176657675}], "attachments": [{"name": "stdout", "source": "2db39bf9-3cd2-489e-b5d9-1dea9c2003cc-attachment.txt", "type": "text/plain"}], "start": 1577176655128, "stop": 1577176657681, "uuid": "115ef35e-ae9c-4bdf-a0b9-bfedc44ad6aa", "historyId": "fd7bdb65f4df5754da250d662b7e39f5", "testCaseId": "70ff1461dbd22ac420eff06f2f2ffeba", "fullName": "testCases.testLogin.test_login.TestSearchPage#test_account_wrong_login", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "这是一个测试账号错误登录的case"}, {"name": "parentSuite", "value": "testCases.testLogin"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSearchPage"}, {"name": "host", "value": "kouhuideMacBook-Air.local"}, {"name": "thread", "value": "31366-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.testLogin.test_login"}]}