{"name": "test_account_wrong_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert '登录信息有误，请确认后重新登录111' in '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t'\n +  where '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t' = <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x10fe414a8>>()\n +    where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x10fe414a8>> = <OperationalLayer.Login.login.LoginOperate object at 0x10fe414a8>.validate_account_not_exist", "trace": "self = <test_cases.test_login.test_login.TestLogin object at 0x10fe47978>, state_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x10fe414a8>\n\n    @allure.story('这是一个测试账号错误登录的case')\n    def test_account_wrong_login(self, state_login_class):\n        '''\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        '''\n        state_login_class.get_login_url()\n        state_login_class.input_account(abnormal_login_data.account, abnormal_login_data.password,\n                                        abnormal_login_data.verification_code)\n        state_login_class.confirm_login_button()\n        time.sleep(1)\n>       assert '登录信息有误，请确认后重新登录111' in state_login_class.validate_account_not_exist()\nE       AssertionError: assert '登录信息有误，请确认后重新登录111' in '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t'\nE        +  where '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t' = <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x10fe414a8>>()\nE        +    where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x10fe414a8>> = <OperationalLayer.Login.login.LoginOperate object at 0x10fe414a8>.validate_account_not_exist\n\ntest_cases/test_login/test_login.py:41: AssertionError"}, "description": "\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "passed", "start": 1577262954757, "stop": 1577262956190}, {"name": "步骤2：输入账号，密码，验证码", "status": "passed", "parameters": [{"name": "account", "value": "'admin1'"}, {"name": "password", "value": "'admin123'"}, {"name": "verification_code", "value": "'1111'"}], "start": 1577262956190, "stop": 1577262956792}, {"name": "步骤3：点击登录按钮", "status": "passed", "start": 1577262956792, "stop": 1577262956859}, {"name": "步骤4：获取账号不存在报错信息", "status": "passed", "start": 1577262957864, "stop": 1577262957884}], "attachments": [{"name": "stdout", "source": "61084528-26db-4ce7-9a53-8abb9ceebc09-attachment.txt", "type": "text/plain"}], "start": 1577262954757, "stop": 1577262957885, "uuid": "4bbc5de5-4543-4651-90a9-8cb6ffe8641a", "historyId": "b308178dd37a299f6d4684f5efc4274c", "testCaseId": "1a9d587fd15c0e192eb1d219417b90b6", "fullName": "test_cases.test_login.test_login.TestLogin#test_account_wrong_login", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "这是一个测试账号错误登录的case"}, {"name": "parentSuite", "value": "test_cases.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "kouhuideMacBook-Air.local"}, {"name": "thread", "value": "77533-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login.test_login"}]}