{"name": "test_wrong_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert '登录信息有误，请确认后重新登录' in '\\n\\t\\t\\t\\t\\t\\t成功\\n\\t\\t\\t\\t\\t'\n +  where '\\n\\t\\t\\t\\t\\t\\t成功\\n\\t\\t\\t\\t\\t' = <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x000002A22D803320>>()\n +    where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x000002A22D803320>> = <OperationalLayer.Login.login.LoginOperate object at 0x000002A22D803320>.validate_account_not_exist", "trace": "self = <test_cases.test_login.test_login.TestLogin object at 0x000002A22D7E0128>, state_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x000002A22D803320>\n\n    @allure.story('这是一个测试密码错误的case')\n    def test_wrong_password(self, state_login_class):\n        '''\n        用例描述：输入正确的账号，输入错误的密码，登录报错\n        :return:\n        '''\n        state_login_class.get_login_url()\n        state_login_class.input_account(wrong_password_login_data.account, wrong_account_login_data.password,\n                                        wrong_password_login_data.verification_code)\n        state_login_class.confirm_login_button()\n        time.sleep(1)\n>       assert '登录信息有误，请确认后重新登录' in state_login_class.validate_account_not_exist()\nE       AssertionError: assert '登录信息有误，请确认后重新登录' in '\\n\\t\\t\\t\\t\\t\\t成功\\n\\t\\t\\t\\t\\t'\nE        +  where '\\n\\t\\t\\t\\t\\t\\t成功\\n\\t\\t\\t\\t\\t' = <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x000002A22D803320>>()\nE        +    where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x000002A22D803320>> = <OperationalLayer.Login.login.LoginOperate object at 0x000002A22D803320>.validate_account_not_exist\n\ntest_cases\\test_login\\test_login.py:86: AssertionError"}, "description": "\n        用例描述：输入正确的账号，输入错误的密码，登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "passed", "start": 1583112034767, "stop": 1583112035275}, {"name": "步骤2：输入账号，密码，验证码", "status": "passed", "parameters": [{"name": "account", "value": "'admin'"}, {"name": "password", "value": "'admin123'"}, {"name": "verification_code", "value": "'1111'"}], "start": 1583112035275, "stop": 1583112035561}, {"name": "步骤3：点击登录按钮", "status": "passed", "start": 1583112035561, "stop": 1583112035620}, {"name": "步骤4：获取账号不存在报错信息", "status": "passed", "start": 1583112036620, "stop": 1583112036635}], "attachments": [{"name": "stdout", "source": "26e16426-3798-42ce-b04a-282ef1a64cfb-attachment.txt", "type": "text/plain"}], "start": 1583112034767, "stop": 1583112036635, "uuid": "ca7dc545-d852-4b4b-80e2-b9e46706d21d", "historyId": "0998e1a31ecc14edfe2c3e0c4ab277a9", "testCaseId": "78e462c49f131d3cc57764bef8f426cf", "fullName": "test_cases.test_login.test_login.TestLogin#test_wrong_password", "labels": [{"name": "story", "value": "这是一个测试密码错误的case"}, {"name": "feature", "value": "登录"}, {"name": "parentSuite", "value": "test_cases.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-IJ0L9OR"}, {"name": "thread", "value": "18308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login.test_login"}]}