{"name": "test_account_wrong_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x109752780>> == '登录信息有误，请确认后重新登录'\n +  where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x109752780>> = <OperationalLayer.Login.login.LoginOperate object at 0x109752780>.validate_account_not_exist", "trace": "self = <testCases.testLogin.test_login.TestSearchPage object at 0x109727b00>, state_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x109752780>\n\n    @allure.story('这是一个测试账号错误登录的case')\n    def test_account_wrong_login(self, state_login_class):\n        '''\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        '''\n        state_login_class.get_login_url()\n        state_login_class.input_account(abnormal_login_data.account, abnormal_login_data.password,\n                                        abnormal_login_data.verification_code)\n        state_login_class.confirm_login_button()\n>       assert state_login_class.validate_account_not_exist == '登录信息有误，请确认后重新登录'\nE       AssertionError: assert <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x109752780>> == '登录信息有误，请确认后重新登录'\nE        +  where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x109752780>> = <OperationalLayer.Login.login.LoginOperate object at 0x109752780>.validate_account_not_exist\n\ntestCases/testLogin/test_login.py:40: AssertionError"}, "description": "\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "passed", "start": 1577172763928, "stop": 1577172764905}, {"name": "步骤2：输入账号，密码，验证码", "status": "passed", "parameters": [{"name": "account", "value": "'admin1'"}, {"name": "password", "value": "'admin123'"}, {"name": "verification_code", "value": "'1111'"}], "start": 1577172764905, "stop": 1577172765609}, {"name": "步骤3：点击登录按钮", "status": "passed", "start": 1577172765610, "stop": 1577172765687}], "attachments": [{"name": "stdout", "source": "1a0a2687-dcc6-44dc-a430-89b2aad82386-attachment.txt", "type": "text/plain"}], "start": 1577172763928, "stop": 1577172765689, "uuid": "3543c9b3-2873-495f-aff9-76905193a90d", "historyId": "fd7bdb65f4df5754da250d662b7e39f5", "testCaseId": "70ff1461dbd22ac420eff06f2f2ffeba", "fullName": "testCases.testLogin.test_login.TestSearchPage#test_account_wrong_login", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "这是一个测试账号错误登录的case"}, {"name": "parentSuite", "value": "testCases.testLogin"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSearchPage"}, {"name": "host", "value": "kouhuideMacBook-Air.local"}, {"name": "thread", "value": "23855-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.testLogin.test_login"}]}