{"name": "test_account_wrong_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x101e7e828>> == '登录信息有误，请确认后重新登录'\n +  where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x101e7e828>> = <OperationalLayer.Login.login.LoginOperate object at 0x101e7e828>.validate_account_not_exist", "trace": "self = <testCases.testLogin.test_login.TestSearchPage object at 0x101e6ddd8>, state_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x101e7e828>\n\n    @allure.story('这是一个测试账号错误登录的case')\n    def test_account_wrong_login(self, state_login_class):\n        '''\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        '''\n        state_login_class.get_login_url()\n        state_login_class.input_account(abnormal_login_data.account, abnormal_login_data.password,\n                                        abnormal_login_data.verification_code)\n        state_login_class.confirm_login_button()\n>       assert state_login_class.validate_account_not_exist == '登录信息有误，请确认后重新登录'\nE       AssertionError: assert <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x101e7e828>> == '登录信息有误，请确认后重新登录'\nE        +  where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x101e7e828>> = <OperationalLayer.Login.login.LoginOperate object at 0x101e7e828>.validate_account_not_exist\n\ntestCases/testLogin/test_login.py:40: AssertionError"}, "description": "\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "passed", "start": 1577173454548, "stop": 1577173456311}, {"name": "步骤2：输入账号，密码，验证码", "status": "passed", "parameters": [{"name": "account", "value": "'admin1'"}, {"name": "password", "value": "'admin123'"}, {"name": "verification_code", "value": "'1111'"}], "start": 1577173456312, "stop": 1577173456965}, {"name": "步骤3：点击登录按钮", "status": "passed", "start": 1577173456965, "stop": 1577173457038}], "attachments": [{"name": "stdout", "source": "895b54d0-ccd4-43e9-9d2b-91f2bcb40e54-attachment.txt", "type": "text/plain"}], "start": 1577173454548, "stop": 1577173457041, "uuid": "60fd9abc-8fc2-4a1e-b152-a8fac6f6a39c", "historyId": "fd7bdb65f4df5754da250d662b7e39f5", "testCaseId": "70ff1461dbd22ac420eff06f2f2ffeba", "fullName": "testCases.testLogin.test_login.TestSearchPage#test_account_wrong_login", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "这是一个测试账号错误登录的case"}, {"name": "parentSuite", "value": "testCases.testLogin"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSearchPage"}, {"name": "host", "value": "kouhuideMacBook-Air.local"}, {"name": "thread", "value": "25191-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.testLogin.test_login"}]}