{"uuid": "380182a9-84e3-4f0e-b55d-fe267d017a11", "children": ["a112cc29-1810-4cc8-bbdc-94716ee2c733"], "befores": [{"name": "add_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button>...</button> is not clickable at point (548, 521). Other element would receive the click: <div class=\"__view\" style=\"position: relative; box-sizing: border-box; min-width: 100%; min-height: 100%; width: -webkit-fit-content;\">...</div>\n  (Session info: chrome=79.0.3945.88)\n  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.0 x86_64)\n\n", "trace": "  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/test_cases/test_user_management/conftest.py\", line 45, in add_user\n    state_add_user_management_class.confirm()\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/OperationalLayer/UserManagement/userManagementAddOperate.py\", line 32, in confirm\n    self.click(UserManagementElement.add_user_confirm_button)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/Base/base.py\", line 51, in click\n    ele.click()\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "点击用户管理", "status": "passed", "start": 1577327103161, "stop": 1577327104532}, {"name": "1.点击添加2.输入编号3.输入姓名4.输入账号", "status": "passed", "parameters": [{"name": "serial_number", "value": "'1'"}, {"name": "name", "value": "'tester'"}, {"name": "account", "value": "'test111'"}], "start": 1577327104533, "stop": 1577327105135}, {"name": "选择所属机构", "status": "passed", "start": 1577327105135, "stop": 1577327105325}, {"name": "点击确定", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button>...</button> is not clickable at point (548, 521). Other element would receive the click: <div class=\"__view\" style=\"position: relative; box-sizing: border-box; min-width: 100%; min-height: 100%; width: -webkit-fit-content;\">...</div>\n  (Session info: chrome=79.0.3945.88)\n  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.0 x86_64)\n\n", "trace": "  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/OperationalLayer/UserManagement/userManagementAddOperate.py\", line 32, in confirm\n    self.click(UserManagementElement.add_user_confirm_button)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/Base/base.py\", line 51, in click\n    ele.click()\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1577327105326, "stop": 1577327105402}], "start": 1577327103161, "stop": 1577327105411}], "start": 1577327103161, "stop": 1577327105630}